using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ReichertsMeatDistributing.Shared
{
    public class ProductRepository
    {
        public List<ProductItem> GetAllProducts()
        {
            var products = new List<ProductItem>();
            products.AddRange(GetBarProducts());
            products.AddRange(GetRestaurantsProducts());
            products.AddRange(GetBurger_BarsProducts());
            products.AddRange(GetCoffee_ShopsProducts());
            products.AddRange(GetConvenience_StoresProducts());

            return products;
        }

        public List<ProductItem> GetBarProducts()
        {
            var products = new List<ProductItem>
            {
                new ProductItem("ANCHOR 624000", "1/4#", "ANCHOR MOZZ STICK BREADED"),
                new ProductItem("ANCHOR POPPER", "1/4#", "ANCHOR JALAPENO POPPERS"),
                new ProductItem("ANCHOR SPICY PICKLE", "4/3#", "ANCHOR SPICY PICKLE FRIES"),
                new ProductItem("APPLE PIE LOG", "72CT.", "APPLE PIE LOG"),
                new ProductItem("BF 4/1 PATTIE INTER", "10#", "INTER 4/1 GROUND BEEF PATTIES"),
                new ProductItem("BF LIP ON WA BEEF AN", "LB.", "WA. BEEF PREM. ANGUS LIP ON"),
                new ProductItem("BF N.Y. STEAK 8oz.", "LB.", "N.Y. STEAK VEIN 20/8oz."),
                new ProductItem("BF PHILLYSTEAK SIR", "40/4oz.", "PHILLY STEAK SIRLOIN"),
                new ProductItem("BF RAYS 5.3 FRITTER", "30/5.33oz", "RAY'S 5.33oz. CUBED BEEF STEAK"),
                new ProductItem("CH BREAST 6oz IQF", "18#", "CHICKEN BREAST B/S 6oz IQF"),
                new ProductItem("CH KOCH 004160", "2/5#", "MINI CHICKEN CORDON BLEU 160CT"),
                new ProductItem("CH KOCH 004172", "2/5#", "KOCH MINI CHICKEN 3 CHEESE&JAL"),
                new ProductItem("CH KOCH 86614", "2/7.5#", "KOCH WING F/C BRD PARTY WING"),
                new ProductItem("CH KOCH 86616", "15#", "KOCH WING SPICY BREADED F/C"),
                new ProductItem("CH TY10475", "2/5#", "TYSON 10475 BREADED TENDER FRI"),
                new ProductItem("CH TY1753", "10#", "TY1753 IQF BRD GIZZARDS 10#"),
                new ProductItem("CHE 120A", "1/5#", "AMERICAN CHEESE SLICED 120CT"),
                new ProductItem("CHE 50", "5#", "CHED/JACK SHREDDED 50/50 FANC"),
                new ProductItem("CHE 80", "1/5#", "PIZZA BLEND CHEESE 80/10/10 5#"),
                new ProductItem("CUSTOM 17649CPAN", "1/12oz.", "BROWN GRAVY MIX"),
                new ProductItem("DAILYS 35112 14-16", "15#", "DAILY'S HONEY CURED BACON 14/1"),
                new ProductItem("DAILYS 47104", "1/5#", "BACON DICED 3/8\""),
                new ProductItem("DAIRY MILK WHIP", "1/2 GAL.", "HEAVY WHIPPING CREAM HALF GALL"),
                new ProductItem("DOLCO 6X6 TO GO", "1/125CT.", "6X6 STYRO HINGED CONTAINER"),
                new ProductItem("DOLCO 9X9 TO GO", "200CT", "DOLCO 9X9 TO GO STYRO CONT"),
                new ProductItem("DRESS BLUE CHEESE", "1 GAL.", "BLUE CHEESE DRESSING #11450"),
                new ProductItem("DRESS COLESLAW", "1 GAL.", "COLESLAW DRESS"),
                new ProductItem("DRESS FRENCH", "1 GAL.", "FRENCH DRESSING"),
                new ProductItem("DRESS HONEY MUST", "1 GAL.", "HONEY MUSTARD DRESS"),
                new ProductItem("DRESS RANCH", "1 GAL.", "RANCH DRESSING #16415"),
                new ProductItem("EG 15", "1/30CT.", "EGGS LOOSE"),
                new ProductItem("FIRM", "10#", "FOSTER FARMS MINI CORNDOGS"),
                new ProductItem("FOSTER FARMS 4001", "1/5#", "FERNANDOS MINI BEEF BURRITO"),
                new ProductItem("FRED GRN BEAN 027572", "6/2#", "FRED'S BATTERED GREEN BEANS"),
                new ProductItem("FRED MINI BURITO B", "1/4#", "FREDS MINI BEEF&BEAN BURRITO 4"),
                new ProductItem("FRED MINI TACO CH", "1/4#", "FRED'S MINI CHICKEN TACOS 4#"),
                new ProductItem("HO 01-2975", "1/64oz", "LOTUS ENERGY BLUE"),
                new ProductItem("HORMEL ITALIAN CHUNK", "2/5#", "HORMEL ITALIAN CHUNK 2/5#"),
                new ProductItem("J & J PRE JAL/CHE", "8/30CT", "JAL & CHE PRETZEL POPPER"),
                new ProductItem("JUICE 46 PINEAPPLE", "1/46oz.", "PINEAPPLE JUICE 100% 46oz."),
                new ProductItem("KIKKOMAN 01150", "5 LB.", "KIKKOMAN TERIYAKI BASTE & GLAZ"),
                new ProductItem("LAMBWESTON 2200D", "4/4#", "LAMBWESTON 2200D POTATO SKIN"),
                new ProductItem("LAMBWESTON J77", "1/5#", "SIMPLOT TATER GEM # 004189"),
                new ProductItem("MARG. NTF WHIPPED", "20#", "GOLD-N-SWEET NTF WHIPPED MARGA"),
                new ProductItem("MAYO GALLON", "1 GAL.", "MAYONNAISE 1 GAL"),
                new ProductItem("NESTLE TRIO ALFREDO", "1/16oz.", "TRIO ALFREDO SAUCE 38502"),
                new ProductItem("OIL FCF 35", "35#", "CLEAR FRY OIL 35#"),
                new ProductItem("PAC 005961", "6000CT.", "SUNNYCARE XPRESS V-FOLD NAPKIN"),
                new ProductItem("PAC 013522", "1/50CT.", "2oz PORTION CUP"),
                new ProductItem("PAC 013531", "1/50CT.", "2oz. LID FOR PORTION CUP"),
                new ProductItem("PAC 780200", "1/100CT.", "MEDIUM P/F VINYL GLOVES"),
                new ProductItem("PAC 780300", "1/100CT.", "LARGE P/F VINYL GLOVES"),
                new ProductItem("PC19400308", "1/100CT.", "FL8V WHITE PLASTIC VENTED LID"),
                new ProductItem("PC19401788", "1/25CT.", "F8 8oz WHITE FOOD CONTAINER"),
                new ProductItem("PC44022004", "1/2000CT.", "WHITE PAPER NAPKIN BAND"),
                new ProductItem("PC68170205", "1/1000CT.", "SIP N STIR NEON ASSORTED 5.25\""),
                new ProductItem("PC68170212", "1/500CT.", "6\" FAT NEON STRAW 500CT"),
                new ProductItem("PC68170218", "1/400CT.", "8\" FAT STRAW"),
                new ProductItem("PC78000011", "4000CT.", "MULTI-FOLD PAPER TOWEL #780000"),
                new ProductItem("PCF1490009", "1/500CT.", "8\" SKINNY NEON STRAW"),
                new ProductItem("PCP PIZZA SAUCE", "1/107oz.", "PARADISO F/P PIZZA SAUCE #3500"),
                new ProductItem("PEP SWISS AMER 19/21", "10#", "SWISS AMERICAN PEPPERONI SLICE"),
                new ProductItem("PEPPERONI VEGAN", "4/2.5#", "VEGAN PEPPERONI SLICE"),
                new ProductItem("PICKLE 3/16 NREF 5GA", "5 GAL.", "PICKLE DILL CHIP 3/16 KK BUC"),
                new ProductItem("PIZZA BOX 12", "50ct", "12\" PIZZA BOX"),
                new ProductItem("PIZZA BOX 16", "50CT.", "16\" PIZZA BOXES WHITE/KRAFT"),
                new ProductItem("PK SAUSAGE FARMLAND", "6#", "FARMLAND PORK SAUSAGE"),
                new ProductItem("PK WING HAWG", "9#", "PORK KC HAWG WILD WINGS"),
                new ProductItem("RICHS 03604", "20/29.5oz.", "RICH'S 16\" PIZZA CRUST"),
                new ProductItem("RICHS 07366", "24/16.6", "RICH'S 12\" PIZZA CRUST"),
                new ProductItem("RICHS 11819", "24/5.2oz.", "PIZZA 10\" CAULIFLOWER CRUST"),
                new ProductItem("ROSES PORKROLL SLICE", "3#", "ROSES PORK ROLL SMOKED SLICED"),
                new ProductItem("SAUCE TARTAR", "1 GAL.", "TARTAR SAUCE"),
                new ProductItem("SEA CLAMSTRIP", "24/4oz.", "SEAWATCH CLAM STRIPS BREADED #"),
                new ProductItem("SEA MRS 70053", "10#", "MRS FRYDAY'S BATTERED COD"),
                new ProductItem("SEA ODY 1-2 HALIBUT", "10#", "ODYSSEY 1-2oz. BATTRED HALIBUT"),
                new ProductItem("SEA SHRIMP BASKET", "12/8oz", "SHRIMP BASKET BREADED"),
                new ProductItem("SEA SHRIMP BRD 16/20", "1/3#", "16/20 SHRIMP BUTTERFLY BREADED"),
                new ProductItem("TACO SHELL 5\"", "200CT", "MISSION 5\" TACO SHELL"),
                new ProductItem("TYSON RL38356", "10#", "RED LABEL BREAST SELECT DICED"),
                new ProductItem("V GREENONION/EACH", "1 BUNCH", "GREEN ONIONS/BUNCH"),
                new ProductItem("V LET", "24CT.", "ICEBURG LETTUCE 24 CT"),
                new ProductItem("V LETR", "1 CASE", "ROMANE LETTUCE WHOLE"),
                new ProductItem("V POT 60", "60CT", "60CT POTATO"),
                new ProductItem("V POT 90", "90 CT", "90ct POTATO"),
                new ProductItem("V POT#2", "BAG", "POTATOES #2 50# BAG"),
                new ProductItem("V TOM", "2 LAYER", "TOMATO XL 5 X6 BOX"),
                new ProductItem("WAMPLER 90080", "10#", "8-1 PRECOOKED SAUSAGE PATTIES"),
                new ProductItem("ANCHOR MUSHROOM", "1/2.5#", "ANCHOR MUSHROOM BUTTER BREADED"),
            };

            return products;
        }

        public List<ProductItem> GetRestaurantsProducts()
        {
            var products = new List<ProductItem>
            {
                new ProductItem("3M 96HEX", "1", "3M DUAL PURPOSE SCOUR PAD #96H"),
                new ProductItem("ANCHOR 624000", "1/4#", "ANCHOR MOZZ STICK BREADED"),
                new ProductItem("ANCHOR MUSHROOM", "1/2.5#", "ANCHOR MUSHROOM BUTTER BREADED"),
                new ProductItem("ANCHOR POPPER", "1/4#", "ANCHOR JALAPENO POPPERS"),
                new ProductItem("BEANS KIDNEY", "1/#10", "KIDNEY BEANS 1/10# CAN"),
                new ProductItem("BEAVER COCKTAIL", "1/13oz.", "BEAVER COCKTAIL SAUCE"),
                new ProductItem("BEAVER COCKTAIL GAL", "1 GAL", "BEAVER COCKTAIL SAUCE GALLON"),
                new ProductItem("BEAVER HR32oz", "1/34oz.", "BEAVER HORSERADISH"),
                new ProductItem("BEAVER MUST G121", "1 GAL.", "BEAVER MUSTARD 1 GALLON"),
                new ProductItem("BF 4/1 PATTIE INTER", "10#", "INTER 4/1 GROUND BEEF PATTIES"),
                new ProductItem("BF 4/1 PATTIE RAY F", "12#", "4/1 RAY'S BEEF PATTIES  12#"),
                new ProductItem("BF GROUND FRESH 5#", "LB.", "GROUND BEEF CHUB 80% LEAN"),
                new ProductItem("BF N.Y. STEAK 8oz.", "LB.", "N.Y. STEAK VEIN  20/8oz."),
                new ProductItem("BF RAYS 12 FRITTER", "9#", "RAY'S 12oz. CUBED BEEF STEAK F"),
                new ProductItem("BF RAYS 5.3 FRITTER", "30/5.33oz", "RAY'S 5.33oz. CUBED BEEF STEAK"),
                new ProductItem("BISC PBUTTERMILK", "120/2.25oz", "6235 PILLSBURY GOLDEN BUTTERMI"),
                new ProductItem("BLACKBERRY PRESERVE", "4#", "BLACKBERRY PRESERVE"),
                new ProductItem("BOUNTY 74657", "1 CT.", "BOUNTY PAPER TOWEL"),
                new ProductItem("BUNN FILTERS 12CUP", "2/500", "COFFEE FILTERS 12 CUP 2/500 CT"),
                new ProductItem("CH BREAST 5oz IQF", "15#", "CHICKEN BREAST B/S 5oz IQF"),
                new ProductItem("CH BREAST B/S RANDOM", "40#", "CHICKEN BREAST FZ B/S"),
                new ProductItem("CH BREAST FRESH", "40#", "CHICKEN BREAST FRESH BNLS/SKLS"),
                new ProductItem("CH KOCH 004160", "2/5#", "MINI CHICKEN CORDON BLEU 160CT"),
                new ProductItem("CH KOCH 86614", "2/7.5#", "KOCH WING F/C BRD PARTY WING"),
                new ProductItem("CH KOCH 86933", "20#", "TENDER HERB BREADED CHICKEN"),
                new ProductItem("CH TY1753", "10#", "TY1753 IQF BRD GIZZARDS 10#"),
                new ProductItem("CH WAFFLE FRITTER", "10#", "WAFFLE CHICKEN BREAST FILLETS"),
                new ProductItem("CHE 120A", "1/5#", "AMERICAN CHEESE SLICED 120CT"),
                new ProductItem("CHE M", "5#", "MOZZARELLA CHEESE SHREDDED 5#"),
                new ProductItem("CHE PARM SHREDD", "1/#5", "PARMISAN CHEESE SHRED 5# BAG"),
                new ProductItem("CHE PEPPJACK  SLICED", "1.5#", "CHEESE PEPPER JACK SLICED"),
                new ProductItem("CHE SC", "1/5#", "CHEDDAR SHREDDED CHEESE MILD 5"),
                new ProductItem("CHE SWISSBLK", "LB.", "GOSSNER SWISS LOAF CHEESE 6/8#"),
                new ProductItem("CHE T", "1/5#", "TILLAMOOK MED CHEDDAR 5#BLOCK"),
                new ProductItem("CHE TILL CHEM SLICE", "2#", "TILLAMOOK MED CHEDDAR SLICED"),
                new ProductItem("CHEESE CURDS", "2/5#", "BREADED WISCONSIN CHEESE CURDS"),
                new ProductItem("CHILI", "1/#10", "NALLEYS  CHILI 6/10 CA"),
                new ProductItem("CLEAN PINE-SOL", "144", "PINE-SOL CLEANER"),
                new ProductItem("CONAGRA JHS22420", "1/#5", "CARAMEL TOPPING"),
                new ProductItem("CONAGRA SWISS47491", "1/50CT.", "SWISS MISS HOT CHOCOLATE 1/50C"),
                new ProductItem("CONT. MILLS 731-0140", "25#", "25# KRUST BUTTERMILK PANCAKE"),
                new ProductItem("CUSTOM 17232ICFPZ", "1#", "AU JUS BASE RED LABEL 1#"),
                new ProductItem("CUSTOM 17649CPAN", "1/12oz.", "BROWN GRAVY MIX"),
                new ProductItem("CUSTOM 17741GPAN", "1/20oz", "BISCUIT PEPPERED GRAVY 17741GP"),
                new ProductItem("CUSTOM 91051EGLDZ", "1#", "CHICKEN BASE 1#"),
                new ProductItem("CUSTOM 93051EGLDZ", "1#", "BEEF BASE 1#"),
                new ProductItem("CUSTOM 95171EGLD", "1#", "CLAM BASE 1#"),
                new ProductItem("CUSTOM 97991EGLDZ", "1#", "HAM BASE 1#"),
                new ProductItem("DAILYS 35112 14-16", "15#", "DAILY'S HONEY CURED BACON 14/1"),
                new ProductItem("DAIRY BUTR PRINTS", "1LB.", "SALTED BUTTER PRINTS"),
                new ProductItem("DAIRY MILK 2%", "1 GAL.", "2% MILK GAL"),
                new ProductItem("DAIRY MILK HG1/2", "1/2 GAL.", "1/2&1/2 HALF GALLON"),
                new ProductItem("DAIRY MILK WHIP", "1/2 GAL.", "HEAVY WHIPPING CREAM HALF GALL"),
                new ProductItem("DAIRY SOUR 5# TUB", "1/5#", "ALPINE FOODS SOUR CREAM TUB"),
                new ProductItem("DAIRYFRESH 49734", "1/15oz.", "WHIPPED TOPPING CAN"),
                new ProductItem("DAWN 886111", "1 GAL.", "VANILLA FLAVORING N&A"),
                new ProductItem("DAWN RH 1372721", "1GAL", "STRAWBERRY TOPPING"),
                new ProductItem("DELI BF ROAST 10%", "LB.", "TOP ROUND ROASTED BEEF FACED C"),
                new ProductItem("DELI MEATBALL 3LB", "3#", "BEEF F/C MEATBALLS 1/2 oz."),
                new ProductItem("DOLCO 6X6 TO GO", "1/125CT.", "6X6 STYRO HINGED CONTAINER"),
                new ProductItem("DOLCO 8 X 5 HOAGIE", "1/50CT.", "HOAGIE SANDWICH HINGED CONTAIN"),
                new ProductItem("DOLCO 8X8 TO GO", "200CT", "DOLCO 8\"x8\"x3\" 1- COMPARTMENT"),
                new ProductItem("DOLCO 9X9 TO GO", "200CT", "DOLCO 9X9 TO GO STYRO CONT"),
                new ProductItem("DOT 288892", "8/60oz.", "APPLE JUICE #32797"),
                new ProductItem("DRESS 1000 ISLAND", "1 GAL.", "THOUSAND ISLAND DRESSING"),
                new ProductItem("DRESS BLUE CHEESE", "1 GAL.", "BLUE CHEESE DRESSING #11450"),
                new ProductItem("DRESS CAESAR CREAMY", "1 GAL.", "CLASSIC CREAMY CAESAR DRESSING"),
                new ProductItem("DRESS FRENCH", "1 GAL.", "FRENCH DRESSING"),
                new ProductItem("DRESS GOLDEN ITALIAN", "1 GAL.", "GOLDEN ITALIAN DRESSING"),
                new ProductItem("DRESS HONEY MUST", "1 GAL.", "HONEY MUSTARD DRESS"),
                new ProductItem("DRESS RANCH", "1 GAL.", "RANCH DRESSING #16415"),
                new ProductItem("DRESS RANCH CHIPOTLE", "1 GAL.", "CHIPOTLE RANCH DRESSING"),
                new ProductItem("EG 15", "1/30CT.", "EGGS  LOOSE"),
                new ProductItem("EG LIQUID 15/2", "15/2#", "PAPETTI'S FRESH LIQUID EGGS"),
                new ProductItem("FARMLAND FLAT 19045", "LB.", "FARMLAND BUFFET DELI HAM"),
                new ProductItem("FIRM", "10#", "FOSTER FARMS MINI CORNDOGS"),
                new ProductItem("FOSTER FARMS 4001", "1/5#", "FERNANDOS  MINI BEEF BURRITO"),
                new ProductItem("FRED BATTERED MUSH", "1/2#", "FRED'S BATTERED MUSHROOM"),
                new ProductItem("FRED MINI BURITO B", "1/4#", "FREDS MINI BEEF&BEAN BURRITO 4"),
                new ProductItem("FRED MINI TACO CH", "1/4#", "FRED'S MINI CHICKEN TACOS 4#"),
                new ProductItem("GARLIC CHOP", "1/32oz", "KGF GARLIC CHOP WATER 32OZ"),
                new ProductItem("GOLDPOINT 5/8 O RING", "4/2.5#", "GOLDPOINT 5/8\" ONION RING"),
                new ProductItem("HD FARMLAND 5/1 MEAT", "10#", "5/1 FARMLAND HOTDOGS ALL MEAT"),
                new ProductItem("HEINZ 526600", "1/5oz.", "HEINZ 57 STEAK SAUCE 5oz"),
                new ProductItem("HO 01-2975", "1/64oz", "LOTUS ENERGY BLUE"),
                new ProductItem("HO 01-2978", "1/64oz", "LOTUS ENERGY PINK"),
                new ProductItem("HO 03-0018", "1/LT.", "ROSE'S  GRENADINE"),
                new ProductItem("HO 03-0428", "5#", "JOHNNY'S SEASONING 1/5#"),
                new ProductItem("HO 06-0522", "1", "BOTTLE SQUEEZE CLEAR 12oz"),
                new ProductItem("HO 08-0690", "24 CT.", "16 GIBRALTAR DURATUFF TUMBLER"),
                new ProductItem("HO 15-0236", "500CT.", "PRE-ASSEMBLED JAVA JACKETS"),
                new ProductItem("HONEY 12/12oz.", "1/12oz.", "GROEB FARMS HONEY BEARS 1/12oz"),
                new ProductItem("HORMEL BB HAM EGG", "80/2oz", "HORMEL HAM,EGG,CHEESE BREAKFAS"),
                new ProductItem("HORMEL BF CRUMBLE", "2/5#", "HORMEL BEEF PIZZA CRUMBLES"),
                new ProductItem("HORMEL BRK SAU 39113", "2/5#", "HORMEL BREAKFAST SAUSAGE CRUMB"),
                new ProductItem("HORMEL ITALIAN CRUMB", "10#", "HORMEL ITALIAN CRUMBLE #11691"),
                new ProductItem("ICE CREAM 3010", "1/3GAL", "VANILLA ICE CREAM 10%"),
                new ProductItem("ICE CREAM 3128", "1/3 GAL.", "CHOCOLATE PB SWIRL ICE CRE"),
                new ProductItem("ICE CREAM 3129", "1/3GAL", "CHOCOLATE ICE CREAM 10%"),
                new ProductItem("ICE CREAM 3169", "1/3 GAL.", "MACKINAC ISLAND FUDGE ICE CREA"),
                new ProductItem("ICE CREAM 3208", "3 GAL.", "STRAWBERRY CHEESECAKE ICE CREA"),
                new ProductItem("JUICE 46 CRANBERRY", "1/46oz.", "CRAN COCKTAIL JUICE 46oz."),
                new ProductItem("JUICE 46 ORANGE", "1/46oz.", "ORANGE JUICE 100% 46oz"),
                new ProductItem("JUICE 5.5 TOMATO", "48/5.5", "TOMATO JUICE CAMPBELL48/5.5oz."),
                new ProductItem("KELLOGGS 80025", "1/100CT.", "CONE CAKE D40"),
                new ProductItem("KELLOGGS 80037", "12/18CT.", "CONE WAFFLE MEDIUM"),
                new ProductItem("LAMBWESTON 30412", "8/2#", "30410 GOURMET BRD ONION RING"),
                new ProductItem("LAMBWESTON 30423", "4/2.5#", "30423 5/8\" BEER BTRD O-RING"),
                new ProductItem("LAMBWESTON C0057", "6/5#", "COO57 COLOSSAL CRISP 3/8 FRIES"),
                new ProductItem("LAMBWESTON C0069", "6/3#", "HASHBROWNS IQF SHRED"),
                new ProductItem("LAMBWESTON J77", "1/5#", "SIMPLOT TATER  GEM # 004189"),
                new ProductItem("LIPTON 289", "96/1oz.", "LIPTON ICED TEA SMOOTH BLEND G"),
                new ProductItem("MASK", "50CT", "3-PLY FACE MASK"),
                new ProductItem("MAYO CARTON", "30#", "MAYONNAISE HD CARTON 30#"),
                new ProductItem("MICHIGAN TURK 46612", "LB.", "46612 BROWN LBL TURKEY BREAST"),
                new ProductItem("NESTLE 05228", "1/#10", "CHEF MATE COUNTRY GRAVY 6/10 C"),
                new ProductItem("NESTLE 35010", "360/.375oz.", "P/C COFFEE MATE CREAMERS 360CT"),
                new ProductItem("OIL EXT VIR OLI OIL", "1GAL", "EXTRA VIRGIN OLIVE OIL"),
                new ProductItem("OIL FCF 35", "35#", "CLEAR FRY OIL 35#"),
                new ProductItem("OIL GRILL 35", "35#", "OIL PAN & GRIDDLE"),
                new ProductItem("OIL OLIVE OIL", "1 GAL.", "NAPOLIAN OLIVE OIL POMACE 1G"),
                new ProductItem("OLIVES LINDSEY", "1/55oz.", "RIPE OLIVES SLICED BLACK"),
                new ProductItem("OLIVES SLICED #10 CN", "1/#10", "OLIVES SLICED RIPE #10 CAN"),
                new ProductItem("ORTEGA 780786", "1 GAL.", "SALSA /PICANTE SAUCE MILD"),
                new ProductItem("P/C BUTTER", "1/200CT.", "BUTTER CONT. CHIPS FOIL WRAPPE"),
                new ProductItem("P/C CRACKER", "500/2CT.", "PREMIUM SALTINE CRACKERS #0151"),
                new ProductItem("P/C CRACKERO", "150/.5oz.", "OYSTER CRACKER 150/.5oz"),
                new ProductItem("P/C CREAMER ASEPTIC", "360/.375oz.", "P/C 1/2 & 1/2 CREAMER ASEPTIC"),
                new ProductItem("P/C CREAMER FRENCH", "288CT.", "P/C FRENCH VANILLA CREAMER"),
                new ProductItem("P/C JAM ASSORTED", "200CT.", "JELLY ASSORTMENT GRAPE MIXED F"),
                new ProductItem("P/C JAM BB", "200CT.", "JAM BLACKBERRY PORTION PACK"),
                new ProductItem("P/C JAM GRAPE", "200/.5oz.", "JELLY GRAPE SINGLE SERV"),
                new ProductItem("P/C JAM STRAWBERRY", "200/.5oz.", "SMUCKERS JAM STRAWBERRY SINGLE"),
                new ProductItem("P/C KET RED GOLD", "1000/9gr.", "P/C KETCHUP RED GOLD FANCY"),
                new ProductItem("P/C MARINARA", "72/2oz.", "MARINARA SAUCE PORTION CUP"),
                new ProductItem("P/C SPLENDA", "100CT.", "SPLENDA SUGAR SUBSTITUTE"),
                new ProductItem("P/C SUG", "2000CT.", "SUGAR PACKET C&H"),
                new ProductItem("P/C SWEET N LOW", "1/50CT.", "SWEET N LOW"),
                new ProductItem("P/C TACO PPI 200CT", "200/9gr.", "P/C PPI TACO SAUCE 200/9GR."),
                new ProductItem("PAC 000832", "1/75CT.", "FIGURE 4-CUP CARRY OUT TRAY"),
                new ProductItem("PAC 005201", "12CT.", "OASIS JUMBO ROLL TOILET"),
                new ProductItem("PAC 006536", "2000CT.", "#25 WAX BAG SANDWICH BAG"),
                new ProductItem("PAC 010112", "200CT", "84842 ZIPLOCK GAL FREEZER BAG"),
                new ProductItem("PAC 010113", "300CT", "#84841 ZIPLOCK BAGS QUART"),
                new ProductItem("PAC 010114", "500CT.", "ZIPPER SANDWICH BAGS CLEAR BAG"),
                new ProductItem("PAC 012722", "200CT.", "BAG REUSE WA"),
                new ProductItem("PAC 013522", "1/50CT.", "2oz PORTION CUP"),
                new ProductItem("PAC 013526", "1/100CT", "4oz PORTION CUP #013526"),
                new ProductItem("PAC 013531", "1/50CT.", "2oz. LID FOR PORTION CUP"),
                new ProductItem("PAC 013532", "1/50CT.", "PORTION LID FOR 3.25 / 4 / 5.5"),
                new ProductItem("PAC 041608", "1/25CT.", "HOT FOOD CUP PAPER 8oz"),
                new ProductItem("PAC 041612", "1/50CT.", "HOT FOOD CUP 12oz."),
                new ProductItem("PAC 077090", "1000CT.", "WRAPPED ROUND TOOTHPICK"),
                new ProductItem("PAC 078636", "500CT.", "#6 BROWN KRAFT BAG"),
                new ProductItem("PAC 078638", "500CT.", "#8 BROWN KRAFT BAG"),
                new ProductItem("PAC 101281", "1", "GRILL BRICKS 8\" X 4\" X 3.5\""),
                new ProductItem("PAC 180752", "1/1000CT.", "SW912 9X12 WHITE SANDWICH WRA"),
                new ProductItem("PAC 185000", "500FT.", "ALUMINUM FOIL 18\" x 500'"),
                new ProductItem("PAC 270681", "1000CT", "PLASTIC HEAVY WEIGHT SPOON"),
                new ProductItem("PAC 300207", "10/100CT.", "PLASTIC KNIFE BLACK HVY WT."),
                new ProductItem("PAC 300208", "10/100CT.", "PLASTIC TEASPOON BLACK HVY WT"),
                new ProductItem("PAC 301026", "1000CT", "PLASTIC HEAVY WEIGHT KNIIFE"),
                new ProductItem("PAC 301027", "1000CT", "FORK PLASTIC HEAVY WEIGHT #U2"),
                new ProductItem("PAC 590608", "1/25CT.", "HOT CONTAINER LID 8oz"),
                new ProductItem("PAC 590612", "1/50CT.", "12oz. HOT CONTAINER LID"),
                new ProductItem("PAC 780200", "1/100CT.", "MEDIUM P/F VINYL GLOVES"),
                new ProductItem("PAC 780300", "1/100CT.", "LARGE P/F VINYL GLOVES"),
                new ProductItem("PAC 780400", "1/100CT.", "X-LARGE P/F VINYL GLOVES"),
                new ProductItem("PAC 815100", "1/250CT", "#100 RED/WHITE PLAID FOOD TRAY"),
                new ProductItem("PAC 880400", "10/100CT.", "NITRILE GLOVES XL"),
                new ProductItem("PASTA FETTUCCINI", "2/10#", "FETTUCCINI PASTA"),
                new ProductItem("PASTA SPAGHETTI 20#", "20#", "SPAGHETTI PASTA 20\""),
                new ProductItem("PC11903044", "GALLON", "53032 FABULOSO LAVENDER CLEANR"),
                new ProductItem("PC16900339", "1 GAL.", "DAWN MANUAL POT & PAN #57445"),
                new ProductItem("PC16904852", "1 GAL", "DAWN HD DEGREASER"),
                new ProductItem("PC19400308", "1/100CT.", "FL8V WHITE PLASTIC VENTED LID"),
                new ProductItem("PC19400411", "1/25CT.", "F12 12oz WHITE FOOD CONTAINER"),
                new ProductItem("PC19400416", "1/20CT.", "F16 16oz WHITE FOOD CONTAINER"),
                new ProductItem("PC19400446", "1/25CT.", "16C18 16OZ WHITE STYROFOAM CUP"),
                new ProductItem("PC19401788", "1/25CT.", "F8 8oz WHITE FOOD CONTAINER"),
                new ProductItem("PC24060206", "1 GAL.", "PUREBRIGHT ULTRA GERM BLEACH"),
                new ProductItem("PC38381594", "1", "DISINFECTING WIPES 35CT"),
                new ProductItem("PC44022004", "1/2000CT.", "WHITE PAPER NAPKIN BAND"),
                new ProductItem("PC49201908", "1/50CT.", "G3632 GUEST CHECK SNG. 50ct"),
                new ProductItem("PC68170218", "1/400CT.", "8\" FAT STRAW"),
                new ProductItem("PC68174303", "1/300CT.", "7.75\" GIANT WRAPPED STRAW"),
                new ProductItem("PC73004383", "1/625CT.", "TALL FOLD DISP NAPKIN"),
                new ProductItem("PC744410201", "1/1000CT.", "4\" CLUB FRILL PICK"),
                new ProductItem("PC75000864", "1/25CT.", "8OZ HOT FOOD CONTAINER PS"),
                new ProductItem("PC75000865", "1/25CT.", "PS 12OZ HOT FOOD CONTAINER"),
                new ProductItem("PC75000870", "1/25CT.", "PS LID FOR HOT FOOD CONTAINER"),
                new ProductItem("PC75001311", "1000CT", "THANK YOU WHITE PLASTIC BAG"),
                new ProductItem("PC76009731", "1/500CT.", "7.75\" JUMBO STRAW WRAPPED"),
                new ProductItem("PC78000005", "6CT", "RIGHT CHOICE WHITE ROLL TOWEL"),
                new ProductItem("PCF1490009", "1/500CT.", "8\" SKINNY NEON STRAW"),
                new ProductItem("PCJ1040001", "1/150CT.", "DINNER NAPKIN DN2015A2"),
                new ProductItem("PEPPER SH", "1/1.5oz.", "PEPPERS SHAKERS TOAST"),
                new ProductItem("PICKLE 3/16 NREF 5GA", "5 GAL.", "PICKLE DILL CHIP 3/16 KK BUC"),
                new ProductItem("PIE APPLE", "1/40oz.", "CYRUS APPLE PIE BAKED 9\""),
                new ProductItem("PIE BANANA CRM", "1/42oz", "CYRUS BANANA CRM PIE 9\""),
                new ProductItem("PIE CHERRY", "1/42oz.", "CYRUS BAKE CHERRY PIE BAKED 9\""),
                new ProductItem("PIE CHOCOLATE CRM", "1/46oz.", "CYRUS CHOCOLATE CREAM"),
                new ProductItem("PIE COCONUT CRM", "1/42oz.", "CYRUS COCONUT CREAM PIE"),
                new ProductItem("PIE FRENCH SILK", "1/30oz.", "CYRUS FRENCH SILK PIE 9\""),
                new ProductItem("PIE LEMON", "1/38oz.", "CYRUS PIE LEMON MERING 9\""),
                new ProductItem("PIE MARION", "1/40oz.", "CYRUS MARION PIE BAKED 9\""),
                new ProductItem("PIE MOCHA CRM", "1/40oz.", "CYRUS MOCHA CRM PIE 9\""),
                new ProductItem("PIE PEACH", "1/40oz.", "CYRUS PEACH PIE BAKED 9\""),
                new ProductItem("PIE PUMPKIN", "EACH", "CYRUS PUMPKIN PIE BAKED 9\""),
                new ProductItem("PIE SOUR CRM LEMON", "1/39oz.", "CYRUS SOUR CRM LEMON PIE 9\""),
                new ProductItem("PIE STRAW/RHUBARB", "1/40oz.", "CYRUS O'LEARY STRAW/RHU PIE"),
                new ProductItem("PIE TURTLE", "1/32oz", "CYRUS TURTLE CHEESCAKE"),
                new ProductItem("PK ITALIAN ROPE SAUS", "LB.", "ITALIAN SAUSAGE MILD ROPE COI"),
                new ProductItem("RED GOLD KET POUCH", "7LB.2oz.", "KETCHUP POUCH REDYA572CD"),
                new ProductItem("RELISH DILL 1G", "1 GAL.", "RELISH DILL 1 GAL"),
                new ProductItem("RELISH SWEET 1G", "1 GAL.", "RELISH SWEET 1 GAL"),
                new ProductItem("ROTEL TOM & GRE CHIL", "12/28oz.", "ROTEL TOMATO DICED & GREEN CHI"),
                new ProductItem("SALT SHAKER", "1/4oz.", "SALT SHAKERS 48/4oz"),
                new ProductItem("SAUCE A1 5oz", "1/5oz.", "A-1 STEAK SAUCE 5oz"),
                new ProductItem("SAUCE SOY 1G", "1 GAL", "SOY SAUCE 4/1 GAL."),
                new ProductItem("SAUCE SPAGHETTI", "1/#10", "SPAGHETTI SAUCE"),
                new ProductItem("SAUCE TARTAR", "1 GAL.", "TARTAR SAUCE"),
                new ProductItem("SAUCE WOR 1G", "1 GAL.", "HEINZ WORCESTERSHIRE SAUCE GA"),
                new ProductItem("SAUERK BUCKET", "2 GAL.", "SAUERKRAUT LONG SHRED BUCKET"),
                new ProductItem("SAUERK GAL.", "1 GAL.", "SAUERKRAUT 4/1GAL"),
                new ProductItem("SEA CLAM CHOP FROZEN", "1/5#", "SEA CLAM MEAT CHOPPED INDIVIDU"),
                new ProductItem("SEA CLAM CHOPPED", "1/51oz.", "CLAM'S CHOPPED SEA"),
                new ProductItem("SEA CLAMSTRIP B SUPR", "1/6#", "SUPER SURF CLAM STRIP BULK PK."),
                new ProductItem("SEA CLAMSTRIP SUPER", "24/4oz.", "SUPER SURF CLAM STRIP BREADED"),
                new ProductItem("SEA DOCKSIDE COD", "10#", "DOCKSIDE COD BEER BATTERED"),
                new ProductItem("SEA OD COD BITES", "10#", "ODY COD BATTERED LOT#37667B-R"),
                new ProductItem("SEA SHRIMP BASKET", "12/8oz", "SHRIMP BASKET BREADED"),
                new ProductItem("SEA SHRIMP BRD 16/20", "1/3#", "16/20 SHRIMP BUTTERFLY BREADED"),
                new ProductItem("SEA TRID COD 491152", "10#", "TRIDENT PUB BATTERED COD 2-3 o"),
                new ProductItem("SKIPPY 84709438", "1/4#", "SKIPPY PEANUTBUTTER CREAMY 6/4"),
                new ProductItem("SPICE 5360", "10oz.", "BAY LEAVES WHOLE"),
                new ProductItem("SPICE 9205", "10.5oz.", "SPAGHETTI SEASONING (SPICY)"),
                new ProductItem("SPICE CINNAMON JAR", "16oz.", "CINNAMON GROUND KORINTJE"),
                new ProductItem("SPICE GARLIC GRA JAR", "22oz.", "GARLIC GRANULES JAR"),
                new ProductItem("SPICE GARLIC GRAN TU", "1/7#", "GARLIC GRANULES TUB"),
                new ProductItem("SPICE ONION CHOP JAR", "1/16oz.", "ONION CHOPPED JAR"),
                new ProductItem("SPICE ONION POWD JAR", "1/18oz.", "ONION POWDER JAR"),
                new ProductItem("SPICE PARSLEY JAR", "3oz.", "PARSLEY FLAKES JAR"),
                new ProductItem("SPICE PEPPER 20M TUB", "5#", "PEPPER BLACK GROUND TUB 20 MES"),
                new ProductItem("SPICE TACO JAR", "22oz.", "TACO SEASONING JAR"),
                new ProductItem("SPICE TACO TUB", "5#", "TACO SEASONING TUB"),
                new ProductItem("SUGAR FOODS 50400", "1200CT", "SUGAR IN RAW 4.5 GRAM 1200CT."),
                new ProductItem("SWEET BABY RAYS BBQ", "1 GAL.", "SWEET BABY RAY'S BBQ SAUCE 044"),
                new ProductItem("SWEET BABY RAYS HOT", "1 GAL.", "SWEET BABY RAY'S HOT SAUCE"),
                new ProductItem("SYRUP MSMB", "1 GAL.", "MRS. BUTTERWORTH MAPLE SYRUP 4"),
                new ProductItem("SYRUP SF", "1/12oz.", "SYRUP SUGAR-FREE 12/12oz."),
                new ProductItem("TABASCO GREEN 5", "1/5oz.", "TABASCO GREEN PEPPER SAUCE 5oz"),
                new ProductItem("TABASCO RED 2", "1/2oz.", "TABASCO SAUCE 2 OZ"),
                new ProductItem("TACO SHELL 5\"", "200CT", "MISSION 5\" TACO SHELL"),
                new ProductItem("TORT DON PANCHO", "12/12ct.", "DON PANCHO TORT 10\" FLOUR"),
                new ProductItem("TYSON RL38351", "10#", "GRILLED CHICK BREAST FILLET 4"),
                new ProductItem("TYSON RL38355", "10#", "GRILLED CHICKEN BREAST STRIP"),
                new ProductItem("TYSON RL38360", "10#", "HOMESTYLE CH BREAST PATTY"),
                new ProductItem("UP DU-701", "12CT", "DUKE TEASPOON 12CT."),
                new ProductItem("UP DU-705", "12CT", "DUKE DINNER FORK 12CT."),
                new ProductItem("UP DU-708", "12CT.", "DUKE DINNER KNIFE 12CT."),
                new ProductItem("V LET", "24CT.", "ICEBURG LETTUCE 24 CT"),
                new ProductItem("V LET EA", "1", "LETTUCE HEAD EACH"),
                new ProductItem("V LETR HEARTS", "1 BAG", "ROMAINE HEARTS"),
                new ProductItem("V LETT SHRED", "5#", "SHREDDED LETTUCE"),
                new ProductItem("V MUSH", "LB.", "MUSHROOMS, MED. 1#"),
                new ProductItem("V ONION LB.", "LB.", "ONIONS LB"),
                new ProductItem("V PEPPERS GREEN LB.", "LB.", "GREEN PEPPER LB./EA."),
                new ProductItem("V POT 60", "60CT", "60CT POTATO"),
                new ProductItem("V POT 90", "90 CT", "90ct POTATO"),
                new ProductItem("V SALAD", "1/5#", "SALAD MIX 80/20 W/COLOR"),
                new ProductItem("V TOM", "2 LAYER", "TOMATO XL 5 X6 BOX"),
                new ProductItem("VC BEAN GR MIX", "1/#10", "CUT BLUE LAKE GREEN BEANS"),
                new ProductItem("VC CORN WHOLE KERNEL", "1/106oz.", "CORN WHOLE KERNEL 1/#10"),
                new ProductItem("VF CORN CUT", "1/2.5#", "CORN CUT FROZEN 12/2.5#"),
                new ProductItem("WAMPLER 90080", "10#", "8-1 PRECOOKED SAUSAGE PATTIES"),
                new ProductItem("WAMPLER 94110", "10#", "1oz. PORK SAUSAGE RAW MILD NO")
            };

            return products;

        }

        public List<ProductItem> GetBurger_BarsProducts()
        {
            var products = new List<ProductItem>
            {
                new ProductItem("ANCHOR MUSHROOM", "1/2.5#", "ANCHOR MUSHROOM BUTTER BREADED"),
                new ProductItem("BEAVER HR32oz", "1/34oz.", "BEAVER HORSERADISH"),
                new ProductItem("BEAVER MUST G121", "1 GAL.", "BEAVER MUSTARD 1 GALLON"),
                new ProductItem("BF B&D 1020", "10#", "B&D BEEF STRIPS BEEFETS 10#"),
                new ProductItem("BF GROUND FRESH 10#", "LB.", "GROUND BEEF 80/20"),
                new ProductItem("BF GROUND FRESH 5#", "LB.", "GROUND BEEF CHUB 80% LEAN"),
                new ProductItem("BF RAYS 3.4 FRITTER", "40/3.4oz.", "RAY'S 3.4oz BEEF STEAK FRITTER"),
                new ProductItem("BF RAYS 5.3 FRITTER", "30/5.33oz", "RAY'S 5.33oz. CUBED BEEF STEAK"),
                new ProductItem("BISC PBUTTERMILK", "120/2.25oz", "6235 PILLSBURY GOLDEN BUTTERMI"),
                new ProductItem("BLACKBERRY PRESERVE", "4#", "BLACKBERRY PRESERVE"),
                new ProductItem("BUNN FILTERS 12CUP", "2/500", "COFFEE FILTERS 12 CUP 2/500 CT"),
                new ProductItem("CH GOLBON STRIP", "10#", "GOLBON CHICKEN STRIP #5010"),
                new ProductItem("CH KOCH 86933", "20#", "TENDER HERB BREADED CHICKEN"),
                new ProductItem("CH KOCH 88876", "2/5#", "KOCH CHIC BREAST FLT"),
                new ProductItem("CHE 120A", "1/5#", "AMERICAN CHEESE SLICED 120CT"),
                new ProductItem("CHE 120S", "1/5#", "SWISS CHEESE SLICED 120CT."),
                new ProductItem("CHE PEPPJACK SLICED", "1.5#", "CHEESE PEPPER JACK SLICED"),
                new ProductItem("CHE SC", "1/5#", "CHEDDAR SHREDDED CHEESE MILD 5"),
                new ProductItem("CHE TILL CHEM SLICE", "2#", "TILLAMOOK MED CHEDDAR SLICED"),
                new ProductItem("CHILI", "1/#10", "NALLEYS CHILI 6/10 CA"),
                new ProductItem("CONAGRA JHS11970", "#10", "RASPBERRY TOPPING"),
                new ProductItem("CONAGRA JHS22000", "1/#10", "MELLOCREAM FUDGE"),
                new ProductItem("CONAGRA JHS22350", "1/#5", "BUTTERSCOTCH TOPPING"),
                new ProductItem("CONAGRA JHS22420", "1/#5", "CARAMEL TOPPING"),
                new ProductItem("CONAGRA JHS22530", "1/#5", "MARSHMALLOW TOPPING"),
                new ProductItem("CONAGRA JHS25465", "1/#5", "PINEAPPLE TOPPING"),
                new ProductItem("CONAGRA JHS25630", "1/3#", "MARSHMALLOW TOPPING TUBS"),
                new ProductItem("CONAGRA SWISS47491", "1/50CT.", "SWISS MISS HOT CHOCOLATE 1/50C"),
                new ProductItem("CONT. MILLS 737-0125", "1/48/.74oz.", "KRUSTEAZ CIDER ALPINE"),
                new ProductItem("DAILYS 35112 14-16", "15#", "DAILY'S HONEY CURED BACON 14/1"),
                new ProductItem("DAIRY ICECREAM 4.5%", "6/.5 GAL.", "VANILLA ICE CREAM MIX 4.5%"),
                new ProductItem("DAIRY MILK 2%", "1 GAL.", "2% MILK GAL"),
                new ProductItem("DAIRY MILK BIB 2%", "5 GAL.", "2% MILK 5 GAL KEEPER"),
                new ProductItem("DAIRY MILK EGG NOG", "1/.5 GAL.", "EGG NOG HALF GALLON"),
                new ProductItem("DAIRY MILK H", "1 GAL.", "MILK HOMO. 1 GAL."),
                new ProductItem("DAIRY SOUR 5# TUB", "1/5#", "ALPINE FOODS SOUR CREAM TUB"),
                new ProductItem("DAIRYFRESH 49734", "1/15oz.", "WHIPPED TOPPING CAN"),
                new ProductItem("DAWN RH 1372721", "1GAL", "STRAWBERRY TOPPING"),
                new ProductItem("DAWN RH 728363", "1 GAL.", "SYRUP STRAWBERRY"),
                new ProductItem("DAWN RH 728389", "1GAL", "SYRUP VANILLA"),
                new ProductItem("DELI SL CORNBEEF", "2.5#", "CORNBEEF EYE ROUND FLAT SLICED"),
                new ProductItem("DELI SL PASTRAMI", "2.5#", "PASTRAMI FLAT SLICED #NPF200CS"),
                new ProductItem("DELI SL ROAST BF", "2.5#", "BEEF BOTTOM ROUND FLAT SLICED"),
                new ProductItem("DELI SL TURKEY 00687", "2#", "OIL BROWNED TURKEY SLICED"),
                new ProductItem("DOLCO 8 X 5 HOAGIE", "1/50CT.", "HOAGIE SANDWICH HINGED CONTAIN"),
                new ProductItem("DOLCO 9X9 TO GO", "200CT", "DOLCO 9X9 TO GO STYRO CONT"),
                new ProductItem("DRESS 1000 ISLAND", "1 GAL.", "THOUSAND ISLAND DRESSING"),
                new ProductItem("DRESS HONEY MUST", "1 GAL.", "HONEY MUSTARD DRESS"),
                new ProductItem("EG 15", "1/30CT.", "EGGS LOOSE"),
                new ProductItem("FARMLAND FLAT 19045", "LB.", "FARMLAND BUFFET DELI HAM"),
                new ProductItem("FIRM", "10#", "FOSTER FARMS MINI CORNDOGS"),
                new ProductItem("FRED BATTERED MUSH", "1/2#", "FRED'S BATTERED MUSHROOM"),
                new ProductItem("FRENCH TOAST STICKS", "5/2#", "MCCAIN FRENCH TOAST STICKS"),
                new ProductItem("FRUIT BANANAS LB.", "LB.", "BANANAS PER LB"),
                new ProductItem("GOLDPOINT 5/8 O RING", "4/2.5#", "GOLDPOINT 5/8\" ONION RING"),
                new ProductItem("GUACAMOLE", "1#", "GUACAMOLE WESTERN STYLE #19342"),
                new ProductItem("HD 24/1# BAR-S", "1#", "BAR-S 1# 8/1 JUMBO FRNKS"),
                new ProductItem("HD HILL 5/1 10\"", "10#", "HILL'S 5/1 10' HOTDOG 10# BOX"),
                new ProductItem("HO 03-0428", "5#", "JOHNNY'S SEASONING 1/5#"),
                new ProductItem("JALAPENO SLICED", "1/#10", "JALAPENO PEPPERS SLICED 1/10#C"),
                new ProductItem("KELLOGGS 80025", "1/100CT.", "CONE CAKE D40"),
                new ProductItem("LAMBWESTON 30412", "8/2#", "30410 GOURMET BRD ONION RING"),
                new ProductItem("LAMBWESTON 30423", "4/2.5#", "30423 5/8\" BEER BTRD O-RING"),
                new ProductItem("LAMBWESTON J77", "1/5#", "SIMPLOT TATER GEM # 004189"),
                new ProductItem("MALT", "1/2.5#", "CARNATION MALTED MILK 40oz"),
                new ProductItem("MARG. NTF WHIPPED", "20#", "GOLD-N-SWEET NTF WHIPPED MARGA"),
                new ProductItem("MAYO CARTON", "30#", "MAYONNAISE HD CARTON 30#"),
                new ProductItem("MCCAIN 5/16 STRAIGHT", "6/5#", "MCCAIN 5/16 STRAIGHT CUT GOLD"),
                new ProductItem("MOORES 10011", "2.5#", "10011 BEER BATRD THICK CUT ONI"),
                new ProductItem("NESTLE 35010", "360/.375oz.", "P/C COFFEE MATE CREAMERS 360CT"),
                new ProductItem("OIL FCF 35", "35#", "CLEAR FRY OIL 35#"),
                new ProductItem("P/C CRACKER", "500/2CT.", "PREMIUM SALTINE CRACKERS #0151"),
                new ProductItem("P/C CRACKERO", "150/.5oz.", "OYSTER CRACKER 150/.5oz"),
                new ProductItem("P/C JAM ASSORTED", "200CT.", "JELLY ASSORTMENT GRAPE MIXED F"),
                new ProductItem("P/C JAM STRAWBERRY", "200/.5oz.", "SMUCKERS JAM STRAWBERRY SINGLE"),
                new ProductItem("P/C PEPPER", "3000/.10gr.", "PEPPER 3/1000/.10 GR"),
                new ProductItem("P/C SALT", "3000/.5gr.", "SALT IODIZED 3M POUCH FLATPACK"),
                new ProductItem("P/C SUG", "2000CT.", "SUGAR PACKET C&H"),
                new ProductItem("P/C SWEET N LOW", "1/50CT.", "SWEET N LOW"),
                new ProductItem("PAC 000832", "1/75CT.", "FIGURE 4-CUP CARRY OUT TRAY"),
                new ProductItem("PAC 002205", "1000CT", "SODA SPOON"),
                new ProductItem("PAC 006534", "2000CT.", "#19 GREASE RESISTANT DRY"),
                new ProductItem("PAC 006536", "2000CT.", "#25 WAX BAG SANDWICH BAG"),
                new ProductItem("PAC 013522", "1/50CT.", "2oz PORTION CUP"),
                new ProductItem("PAC 013531", "1/50CT.", "2oz. LID FOR PORTION CUP"),
                new ProductItem("PAC 041608", "1/25CT.", "HOT FOOD CUP PAPER 8oz"),
                new ProductItem("PAC 041612", "1/50CT.", "HOT FOOD CUP 12oz."),
                new ProductItem("PAC 078635", "500CT.", "#4 BROWN KRAFT BAG"),
                new ProductItem("PAC 078638", "500CT.", "#8 BROWN KRAFT BAG"),
                new ProductItem("PAC 101282", "1/10CT.", "GRIDDLE CLEANING PAD #S460"),
                new ProductItem("PAC 101283", "1/20CT.", "GRILL SCREENS 4\" X 5.5\" #GS10"),
                new ProductItem("PAC 101415", "1 RL", "BUTCHER PAPER WHITE 15\" X 1300"),
                new ProductItem("PAC 121180", "1100 FT. R0LL", "18\" FREEZER PAPER # 12118"),
                new ProductItem("PAC 182175", "1/1000CT.", "WAXED PICK UP PAPER WHITE 6X6\""),
                new ProductItem("PAC 270681", "1000CT", "PLASTIC HEAVY WEIGHT SPOON"),
                new ProductItem("PAC 301026", "1000CT", "PLASTIC HEAVY WEIGHT KNIIFE"),
                new ProductItem("PAC 301027", "1000CT", "FORK PLASTIC HEAVY WEIGHT #U2"),
                new ProductItem("PAC 580000", "1/250CT.", "1/2 FOLD TOILET SEAT COVER"),
                new ProductItem("PAC 590608", "1/25CT.", "HOT CONTAINER LID 8oz"),
                new ProductItem("PAC 590612", "1/50CT.", "12oz. HOT CONTAINER LID"),
                new ProductItem("PAC 654867", "500CT.", "#12 BROWN KRAFT BAG"),
                new ProductItem("PAC 768000", "1000CT.", "WHITE SOUP SPOON HVY. #HPPSSWD"),
                new ProductItem("PAC 780200", "1/100CT.", "MEDIUM P/F VINYL GLOVES"),
                new ProductItem("PAC 815000", "1/250CT.", "#50 1/2-LB FOOD TRAY RED CHECK"),
                new ProductItem("PAC 815100", "1/250CT", "#100 RED/WHITE PLAID FOOD TRAY"),
                new ProductItem("PAC 815200", "1/250CT", "#200 2-LB FOOD TRAY RED CHECK"),
                new ProductItem("PAC 815250", "1/250CT.", "#250 RED/WHITE PLAID FOOD TRAY"),
                new ProductItem("PAC 815300", "1/250CT", "#300 RED/WHITE PLAID FOOD TRAY"),
                new ProductItem("PAR-WAY 22021", "1/21oz.", "COATING VEGALENE AEROSOL"),
                new ProductItem("PC17800075", "1/250CT.", "JR SIZE BURGER CUPS #610750"),
                new ProductItem("PC17802240", "1/250CT.", "10\" PAPER HOT DOG TRAY"),
                new ProductItem("PC18108200", "1/500CT.", "8\" MED WEIGHT HOT DOG TRAY"),
                new ProductItem("PC18400717", "400CT.", "FT LONG HD CLAM SHELL"),
                new ProductItem("PC19400308", "1/100CT.", "FL8V WHITE PLASTIC VENTED LID"),
                new ProductItem("PC19400349", "1/100CT.", "DL18 ESPRESSO STYLE DOME LID"),
                new ProductItem("PC19400411", "1/25CT.", "F12 12oz WHITE FOOD CONTAINER"),
                new ProductItem("PC19400446", "1/25CT.", "16C18 16OZ WHITE STYROFOAM CUP"),
                new ProductItem("PC19400576", "1/100", "DT18 WHITE PLASTIC LID"),
                new ProductItem("PC19401788", "1/25CT.", "F8 8oz WHITE FOOD CONTAINER"),
                new ProductItem("PC24060206", "1 GAL.", "PUREBRIGHT ULTRA GERM BLEACH"),
                new ProductItem("PC49201908", "1/50CT.", "G3632 GUEST CHECK SNG. 50ct"),
                new ProductItem("PC75000864", "1/25CT.", "8OZ HOT FOOD CONTAINER PS"),
                new ProductItem("PC75000865", "1/25CT.", "PS 12OZ HOT FOOD CONTAINER"),
                new ProductItem("PC75000870", "1/25CT.", "PS LID FOR HOT FOOD CONTAINER"),
                new ProductItem("PC75005230", "10/100CT.", "LATEX GLOVES PF MEDIUM"),
                new ProductItem("PCJ1040001", "1/150CT.", "DINNER NAPKIN DN2015A2"),
                new ProductItem("PICKLE 3/16 NREF 5GA", "5 GAL.", "PICKLE DILL CHIP 3/16 KK BUC"),
                new ProductItem("PLEASE DELIVER", "", "PLEASE DELIVER"),
                new ProductItem("RELISH DILL 1G", "1 GAL.", "RELISH DILL 1 GAL"),
                new ProductItem("RELISH SWEET 1G", "1 GAL.", "RELISH SWEET 1 GAL"),
                new ProductItem("SALT 25", "25#", "SALT 25# BAG"),
                new ProductItem("SAUCE TAPATIO", "1/5oz.", "TAPATIO HOT SAUCE"),
                new ProductItem("SAUERK GAL.", "1 GAL.", "SAUERKRAUT 4/1GAL"),
                new ProductItem("SEA BR3", "1/6#", "ICELANTIC BREADED COD PORTOINS"),
                new ProductItem("SEA CLAMSTRIP", "24/4oz.", "SEAWATCH CLAM STRIPS BREADED #"),
                new ProductItem("SEA MRS 70053", "10#", "MRS FRYDAY'S BATTERED COD"),
                new ProductItem("SEA SHRIMP BASKET", "12/8oz", "SHRIMP BASKET BREADED"),
                new ProductItem("SEA SHRIMP BRD 16/20", "1/3#", "16/20 SHRIMP BUTTERFLY BREADED"),
                new ProductItem("SEA TRID COD 491152", "10#", "TRIDENT PUB BATTERED COD 2-3 o"),
                new ProductItem("SKIPPY 84709438", "1/4#", "SKIPPY PEANUTBUTTER CREAMY 6/4"),
                new ProductItem("SOUP 7 BEAN MEDLEY", "1/4#", "SOUP 7 BEAN MEDLEY"),
                new ProductItem("SOUP BEAN & HAM", "4#", "BEAN & HAM"),
                new ProductItem("SOUP BOSTON CLAM CHO", "1/4#", "CLAM CHOWDER-BOST"),
                new ProductItem("SOUP CHICK DUMPLING", "4#", "SOUP CHICKEN & DUMPLING"),
                new ProductItem("SOUP CHICK NOODLE", "1/4#", "SOUP HOMESTYLE CHICKEN NOODLE"),
                new ProductItem("SOUP CREAM OF BROC", "1/4#", "SOUP CREAM BROCCOLI W/CHEESE"),
                new ProductItem("SOUP CRM OF POTATO", "1/4#", "SOUP CREAM OF POTATOE/BACON"),
                new ProductItem("SOUP IVAR ZESTY TOMA", "1/4#", "SS TOMATO ZESTY PARM"),
                new ProductItem("SOUP IVAR ZUPPA TOSC", "1/4#", "ZUPPA TOSCANA RTU SOUP #978"),
                new ProductItem("SOUP VEG BEEF/BAR", "1/4#", "SOUP VEG BEEF BARLEY"),
                new ProductItem("SPICE GARLIC PEPPER", "1/16oz.", "GARLIC PEPPER BLEND JAR"),
                new ProductItem("SPICE GARLIC POW TUB", "5.5 LB.", "GARLIC POWDER CHINESE TUB"),
                new ProductItem("SPICE PEPPER 20M TUB", "5#", "PEPPER BLACK GROUND TUB 20 MES"),
                new ProductItem("SPICE PEPPER COUR TU", "5#", "PEPPER BLACK COURSE TUB 14 MES"),
                new ProductItem("SUGAR 25", "25#", "GRANULATED SUGAR #25"),
                new ProductItem("SWEET BABY RAYS BBQ", "1 GAL.", "SWEET BABY RAY'S BBQ SAUCE 044"),
                new ProductItem("TTCHEC", "1/750ML", "TORANI CHEESECAKE 750ML"),
                new ProductItem("TTCHER", "1/750ML", "TORANI CHERRY 750ML"),
                new ProductItem("TTCRDM", "1/750ML", "TORANI CREME DE MENTHE 750ML"),
                new ProductItem("TTGREEN APPLE", "1/750ML", "TORANI GREEN APPLE 750ML"),
                new ProductItem("TTORADF750", "1/750ML", "TORANI ORANGE DAIRY FRIENDLY"),
                new ProductItem("TTPM750", "1/750ML", "TORANI PEPPERMINT 750ML"),
                new ProductItem("TYSON RL38351", "10#", "GRILLED CHICK BREAST FILLET 4"),
                new ProductItem("TYSON RL38355", "10#", "GRILLED CHICKEN BREAST STRIP"),
                new ProductItem("TYSON RL38360", "10#", "HOMESTYLE CH BREAST PATTY"),
                new ProductItem("V LET", "24CT.", "ICEBURG LETTUCE 24 CT"),
                new ProductItem("V LET EA", "1", "LETTUCE HEAD EACH"),
                new ProductItem("V MUSH", "LB.", "MUSHROOMS, MED. 1#"),
                new ProductItem("V ONION", "BAG", "YELLOW ONIONS 50# BAG"),
                new ProductItem("V TOM", "2 LAYER", "TOMATO XL 5 X6 BOX"),
                new ProductItem("WAMPLER 90080", "10#", "8-1 PRECOOKED SAUSAGE PATTIES"),
                new ProductItem("WAMPLER 91160", "10#", "1oz. PRECOOKED SAUSAGE LINK")
            };

            return products;

        }

        public List<ProductItem> GetCoffee_ShopsProducts()
        {


            List<ProductItem> products = new List<ProductItem>
            {
                new ProductItem("BT CARAMEL LATTE", "1/3.5#", "BIG TRAIN CARAMEL CREME"),
                new ProductItem("BT CHOC PB", "1/3.5#", "BT CHOCOLATE PEANUTBUTTER"),
                new ProductItem("BT COOKIES & CREAM", "1/3.5#", "BIG TRAIN COOKIES & CREAM"),
                new ProductItem("BT JAVA CHIP", "3.5#", "BIG TRAIN JAVA CHIP"),
                new ProductItem("BT SMOOTHIE", "1/3.5#", "BIG TRAIN VANILLA SMOOTHIE"),
                new ProductItem("BT SPICED CHIA", "3.5#", "BIG TRAIN SPICED CHIA TEA"),
                new ProductItem("BT VANILLA CHIA", "3.5#", "BIG TRAIN VANILLA CHIA"),
                new ProductItem("BT VANILLA LATTE", "1/3.5#", "BIG TRAIN VANILLA LATTE"),
                new ProductItem("CONAGRA SWISS6211", "1/2#", "SWISS MISS HOT CHOCOLATE BULK"),
                new ProductItem("DAIRY MILK WHIP", "1/2 GAL.", "HEAVY WHIPPING CREAM HALF GALL"),
                new ProductItem("DAIRYFRESH 49734", "1/15oz.", "WHIPPED TOPPING CAN"),
                new ProductItem("DON MIGUEL 18431", "12/7oz.", "BACON EGG & CHEESE BURRITO"),
                new ProductItem("DON MIGUEL 18432", "12/7oz.", "SAUSAGE & EGG BURRITO"),
                new ProductItem("DON MIGUEL WH 9 YDS", "12/7oz.", "WHOLE 9 YARDS BURRITO"),
                new ProductItem("GHIR WHITE CHOC. 10#", "10#", "GHIRADELLI W. CHOCOLATE 10#"),
                new ProductItem("HER POUCH 64", "4/64oz.", "HERSHEY CHOCOLATE SYRUP POUCH"),
                new ProductItem("HO 01-1784", "12 CT", "MOD VARIETY"),
                new ProductItem("HO 01-2710/2711", "8CT", "UMPQUA OATMEAL"),
                new ProductItem("HO 01-2975", "1/64oz", "LOTUS ENERGY BLUE"),
                new ProductItem("HO 01-2978", "1/64oz", "LOTUS ENERGY PINK"),
                new ProductItem("HO 01-2979", "1/64oz.", "LOTUS ENERGY POWER UP"),
                new ProductItem("HO 01-2980", "1/64oz", "LOTUS ENERGY PURPLE"),
                new ProductItem("HO 01-2981", "1/64oz", "LOTUS ENERGY GOLD (RED)"),
                new ProductItem("HO 01-2982", "1/64oz", "LOTUS ENERGY SKINNY BLUE"),
                new ProductItem("HO 01-2983", "1/64oz", "LOTUS SKINNY PINK"),
                new ProductItem("HO 01-2984", "1/64oz", "LOTUS ENERGY SKINNY GOLD"),
                new ProductItem("HO 01-2985", "64oz.", "LOTUS ENERGY LEMONADE"),
                new ProductItem("HO 01-3059", "1/64oz", "LOTUS CREAM CONCENTRATE"),
                new ProductItem("HO 01-3064", "EA", "LOTUS PUMP"),
                new ProductItem("HO 01-3306", "2.5#", "BARISTA 22 SF WHITE CHOC POW"),
                new ProductItem("HO 04-0462", "1/450CT.", "STRAWS ZOMBIE RED 10\""),
                new ProductItem("HO 13-0706", "1", "DIGITAL THERMOMETER 3\""),
                new ProductItem("HO 15-0236", "500CT.", "PRE-ASSEMBLED JAVA JACKETS"),
                new ProductItem("ICE 8/5", "8/5#", "ICE 8/5#  BAGS"),
                new ProductItem("ICE BLOCK 3/10#", "3/10#", "ICE BLOCK 3/10#"),
                new ProductItem("JJ PRE CHEDDAR CH", "20/6.25", "JJ PRETZEL CHEDDAR CHEESE"),
                new ProductItem("JJ PRE JALAPENO CHE", "20/6.25", "JJ PRETZEL JALAPENO CHEESE"),
                new ProductItem("JJ PRE SWEET CREAM", "20/6.25", "PRETZEL SWEET CREAM"),
                new ProductItem("KARAT 8oz HOT CUP WH", "1/50CT.", "KARAT 8oz. HOT CUP WHITE"),
                new ProductItem("KARAT 8oz LID HOT", "1/50CT.", "LID HOT SIPPER WHITE 8oz"),
                new ProductItem("KARAT CLEAR 12oz CUP", "1/50CT.", "KARAT 12oz CLEAR CUP #C-KC12"),
                new ProductItem("KARAT CLEAR 16oz CUP", "1/50CT.", "KARAT 16oz CLEAR CUP #C-KC16"),
                new ProductItem("KARAT CLEAR 20oz CUP", "1/50CT.", "KARAT 20oz CLEAR CUP #C-KC20"),
                new ProductItem("KARAT CLEAR 24oz CUP", "1/50CT.", "KARAT 24oz CLEAR CUP #C-KC24"),
                new ProductItem("KARAT CLEAR 32oz CUP", "1/25CT.", "KARAT 32OZ CLEAR CUP#C-KCL1045"),
                new ProductItem("KARAT CLEAR 32oz LID", "1/50CT.", "KARAT 32OZ FLAT LID #PTLIDF107"),
                new ProductItem("KARAT CLEAR 8oz. CUP", "1/50CT.", "KARAT 8oz. CLEAR PLASTIC CUP #"),
                new ProductItem("KARAT DOME 32oz LID", "1/50CT.", "32OZ CLEAR PLASTIC DOME LID W/"),
                new ProductItem("KARAT HOT 16oz.", "1/50CT.", "16oz KARAT HOT CUP 16oz. # K-C"),
                new ProductItem("KARAT LID 8oz FLAT", "1/100ct", "LID CLEAR FLAT SLOTTED 8oz"),
                new ProductItem("KARAT LID COLD DOME", "1/50CT.", "KARAT DOME LID #PTLIDD"),
                new ProductItem("KARAT LID COLD FLAT", "1/50CT.", "KARAT FLAT LID #PTLIDF"),
                new ProductItem("KARAT LID SIP BLACK", "1/50CT.", "KARAT SIP LID BLACK FOR PAPER"),
                new ProductItem("NEMO 104", "36/3oz.", "NEMOS CHOC CAKE36/3oz"),
                new ProductItem("NEMO 204", "36/3oz.", "NEMO'S CARROT CAKE 36/3OZ #204"),
                new ProductItem("NEMO 304", "36/3oz", "NEMO'S BANANA CAKE 36/3oz #304"),
                new ProductItem("PAC 000832", "1/75CT.", "FIGURE 4-CUP CARRY OUT TRAY"),
                new ProductItem("PACIFIC ALMOND MILK", "1/32oz.", "PACIFIC ALMOND ORIGINAL"),
                new ProductItem("PACIFIC COCONUT MILK", "1/32oz", "PACIFIC COCONUT MILK"),
                new ProductItem("PACIFIC HEMP MILK", "1/32oz", "HEMP MILK"),
                new ProductItem("PACIFIC OAT MILK", "1/32oz", "PACIFIC OAT MILK BARISTA 32oz."),
                new ProductItem("PACIFIC SOY VANILLA", "1/32oz", "PACIFIC SOY BLENDERS VANILLA"),
                new ProductItem("PC18202327", "1/25CT.", "424MSN-0029 MISTIQUE 24OZ"),
                new ProductItem("PC18202352", "1/50CT.", "12OZ BLACK HOT CUP"),
                new ProductItem("PC18206005", "1/100CT.", "TLP316 SOLO WHITE TRAVELER LID"),
                new ProductItem("PC18206006", "1/100CT.", "TLB316 BLACK TRAVEL LID"),
                new ProductItem("PC18206112", "1/100CT.", "TL38B SOLO BLACK TRAVELER LID"),
                new ProductItem("PC18206420", "1/50CT.", "420MS 20OZ MISTIQUE HOT CUP"),
                new ProductItem("PC18206421", "1/50CT.", "16OZ BLACK HOT CUP"),
                new ProductItem("PC18206423", "1/50CT.", "378MS 8OZ MISTIQUE HOT CUP"),
                new ProductItem("PC68170212", "1/500CT.", "6\" FAT NEON STRAW 500CT"),
                new ProductItem("PC68170218", "1/400CT.", "8\"  FAT STRAW"),
                new ProductItem("PCF1490009", "1/500CT.", "8\" SKINNY NEON STRAW"),
                new ProductItem("SF M BN", "6CT.", "BANANA NUT MUFFIN TOP"),
                new ProductItem("SF M CC", "6CT.", "CHOC CHIP MUFFIN TOP"),
                new ProductItem("SF M LP", "6CT.", "LEMON POPPYSEED MUFFIN TOP"),
                new ProductItem("SF M RAS", "6CT.", "RASPBERRY MUFFIN TOP"),
                new ProductItem("TASTEE BF & BROCCO", "1/22oz.", "TASTEE CHOICE BEEF & BROCCOLI"),
                new ProductItem("TASTEE CHICK ALFREDO", "1/24oz", "TASTEE CHICKEN ALFREDO"),
                new ProductItem("TORANI SYRUP PUMP", "1", "TORANI SYRUP BOTTLE PUMP .25oz"),
                new ProductItem("TTAL", "1/750ML", "TORANI ALMOND ROCA 750ML"),
                new ProductItem("TTAM", "1/750ML", "TORANI AMARETTO 750ML"),
                new ProductItem("TTAP", "1/750ML", "TORANI APPLE 750ML"),
                new ProductItem("TTBAN", "1/750ML", "TORANI CREME DE BANANA 750ML"),
                new ProductItem("TTBB", "1/750ML", "TORANI BLACKBERRY 750ML"),
                new ProductItem("TTBLUB", "1/750ML", "TORANI BLUEBERRY 750ML"),
                new ProductItem("TTBLUR", "1/750ML", "TORANI BLUE RASPBERRY 750ML"),
                new ProductItem("TTBROSC", "1/750ML", "TORANI BROWN SUGAR CINNAMON"),
                new ProductItem("TTBUP", "1/750ML", "TORANI BUTTER PECAN"),
                new ProductItem("TTBUR", "1/750ML", "TORANI BUTTER RUM 750ML"),
                new ProductItem("TTBUS", "1/750ML", "TORANI BUTTERSCOTCH 750ML"),
                new ProductItem("TTCAN", "1/750ML", "TORANI CANTALOUPE 750ML"),
                new ProductItem("TTCAR", "1/750ML", "TORANI CARAMEL 750ML"),
                new ProductItem("TTCHEC", "1/750ML", "TORANI CHEESECAKE 750ML"),
                new ProductItem("TTCHER", "1/750ML", "TORANI CHERRY 750ML"),
                new ProductItem("TTCIN", "1/750ML", "TORANI CINNAMON 750ML"),
                new ProductItem("TTCRDM", "1/750ML", "TORANI CREME DE MENTHE 750ML"),
                new ProductItem("TTCUP", "1/750ML", "TORANI CUPCAKE750ML"),
                new ProductItem("TTET", "1/750ML", "TORANI ENGLISH TOFFEE 750ML"),
                new ProductItem("TTFRV", "1/750ML", "TORANI FRENCH VANILLA 750ML"),
                new ProductItem("TTGREEN APPLE", "1/750ML", "TORANI GREEN APPLE 750ML"),
                new ProductItem("TTGUAVA", "1/750ML", "TORANI GUAVA 750ML"),
                new ProductItem("TTHN", "1/750ML", "TORANI HAZELNUT 750ML"),
                new ProductItem("TTHUCKLEBERRY", "1/750ML", "TORANI HUCKLEBERRY 750ML"),
                new ProductItem("TTIC", "1/750ML", "TORANI IRISH CREAM 750ML"),
                new ProductItem("TTKIWI", "1/750ML", "TORANI KIWI 750ML"),
                new ProductItem("TTLAV", "1/750ML", "TORANI LAVENDER 750ML"),
                new ProductItem("TTLIME", "1/750ML", "TORANI LIME 750ML"),
                new ProductItem("TTMACADAMIA", "1/750ML", "TORANI MACADAMIA 750ML"),
                new ProductItem("TTMANGO", "1/750ML", "TORANI MANGO 750ML"),
                new ProductItem("TTMAPLE", "1/750ML", "TORANI MAPLE 750ML"),
                new ProductItem("TTORADF750", "1/750ML", "TORANI ORANGE DAIRY FRIENDLY"),
                new ProductItem("TTPB", "1/750ML", "TORANI PEANUT BUTTER 750ML"),
                new ProductItem("TTPEA750", "1/750ML", "TORANI PEACH 750ML"),
                new ProductItem("TTPF750", "1/750ML", "TORANI PASSION FRUIT 750ML"),
                new ProductItem("TTPGF750", "1/750ML", "TORANI RUBY RD GRAPFRUIT 750ML"),
                new ProductItem("TTPIN750", "1/750ML", "TORANI PINEAPPLE 750ML"),
                new ProductItem("TTPM750", "1/750ML", "TORANI PEPPERMINT 750ML"),
                new ProductItem("TTPOM750", "1/750ML", "TORANI POMEGRANATE 750ML"),
                new ProductItem("TTPP", "1/750ML", "TORANI PRICKLY PEAR"),
                new ProductItem("TTPUMPKIN SPICE", "1/750ML", "TORANI PURE PUMPKIN SPICE 750"),
                new ProductItem("TTRB750", "1/750ML", "TORANI ROOTBEER 750ML"),
                new ProductItem("TTRED RASPBERRY", "1/750ML", "TORANI RED RASPBERRY 750ML"),
                new ProductItem("TTSALTED CARAMEL", "1/750ML", "TORANI SALTED CARAMEL 750ML"),
                new ProductItem("TTSAUCE CARAMEL", "1/64oz.", "TORANI CARAMEL SAUCE"),
                new ProductItem("TTSFALM750", "1/750ML", "TORANI SUGAR FREE ALMOND 750ML"),
                new ProductItem("TTSFBLUR", "1/750ML", "TORANI SUGAR FREE BLUE RASP"),
                new ProductItem("TTSFBSUGCIN750ML", "1/750ML", "TORANI S/F BRN SUGAR CINNAMON"),
                new ProductItem("TTSFCAR750", "1/750ML", "TORANI SUGAR FREE CARMEL 750ML"),
                new ProductItem("TTSFET750", "1/750ML", "TORANI SUGAR FREE ENGLISH TOFF"),
                new ProductItem("TTSFHN750", "1/750ML", "TORANI SUGAR FREE HAZELNUT 750"),
                new ProductItem("TTSFIC750", "1/750ML", "TORANI SUGAR FREE IRISH CREME"),
                new ProductItem("TTSFMANGO", "1/750ML", "TORANI SUGAR FREE MANGO"),
                new ProductItem("TTSFORG750", "1/750ML", "TORANI SUGAR FREE ORANGE"),
                new ProductItem("TTSFPB750", "1/750ML", "TORANI S/F PEANUT BUTTER 750ML"),
                new ProductItem("TTSFPEACH", "1/750ML", "TORANI SUGAR FREE PEACH 750ML"),
                new ProductItem("TTSFPINE", "1/750ML", "TORANI SUGAR FREE PINEAPPLE"),
                new ProductItem("TTSFPM", "1/750ML", "TORANI SUGAR FREE PEPPERMINT"),
                new ProductItem("TTSFRAS750", "1/750ML", "TORANI SUGAR FREE RASPBERRY 75"),
                new ProductItem("TTSFSALTCAR750", "1/750ML", "TORANI SF SALTED CARAMEL 750ML"),
                new ProductItem("TTSFSAUCECARM", "1/64oz.", "TORANI SF CARAMEL SAUCE 1/64OZ"),
                new ProductItem("TTSFSTR", "1/750ML", "TORANI SUGAR FREE STRAWBERRY"),
                new ProductItem("TTSFVAN750", "1/750ML", "TORANI SUGAR FREE VANILLA 750M"),
                new ProductItem("TTSFVANB750", "1/750ML", "TORANI SF VANILLA BEAN"),
                new ProductItem("TTSFWCHOC", "1/750ML", "TORANI SUGAR FREE WHITE CHOC"),
                new ProductItem("TTTOM750", "1/750ML", "TORANI TOASTMARSH 750ML"),
                new ProductItem("BOUNTY 74657", "1 CT.", "BOUNTY PAPER TOWEL"),
                new ProductItem("DAIRY MILK 2%", "1 GAL.", "2% MILK GAL"),
                new ProductItem("DAIRY MILK HG1/2", "1/2 GAL.", "1/2&1/2 HALF GALLON"),
                new ProductItem("HO 01-3213", "64oz.", "WHITE LOTUS"),
                new ProductItem("PC18201296", "350CT.", "IC20 DUO PAPER HOT CUP 20OZ"),
                new ProductItem("PC18201297", "525CT", "IC16 DUO PAPER HOT CUP 16OZ"),
                new ProductItem("PC18201298", "600CT", "IC12 DUO PAPER HOT CUP 12OZ"),
                new ProductItem("PC18201974", "20/50CT.", "IC8 DUO PAPER HOT CUP 8OZ"),
                new ProductItem("PC68170205", "1/1000CT.", "SIP N STIR NEON ASSORTED 5.25\""),
                new ProductItem("SF M AM", "6CT.", "APPLE MAPLE MUFFIN TOP"),
                new ProductItem("SF M OC", "6CT.", "ORANGE CRANBERRY MUFFIN TOP"),
                new ProductItem("TTCOC", "1/750ML", "TORANI COCONUT 750ML"),
                new ProductItem("TTCOF", "1/750ML", "TORANI COFFEE 750ML"),
                new ProductItem("TTORG750", "1/750ML", "TORANI ORGEAT (ALMOND) 750ML"),
                new ProductItem("TTSAUCE PEPPERMINT", "1/64oz", "TORANI PEPPERMINT BARK SAUCE"),
                new ProductItem("TTSFCOC", "1/750ML", "TORANI SUGAR FREE COCONUT"),
                new ProductItem("TTSFWATER750", "1/750ML", "TORANI SUGAR FREE WATERMELON"),
                new ProductItem("TTSHBR", "1/750ML", "TORANI SHORTBREAD 750ML"),
                new ProductItem("TTSTR750", "1/750ML", "TORANI STRAWBERRY 750ML"),
                new ProductItem("TTVAN750", "1/750ML", "TORANI VANILLA 750ML"),
                new ProductItem("TTVANB750", "1/750ML", "TORANI VANILLA BEAN 750ML"),
                new ProductItem("TTWM750", "1/750ML", "TORANI WATERMELON 750ML"),
            };

            return products;
        }

        public List<ProductItem> GetConvenience_StoresProducts()
        {
            var products = new List<ProductItem>
            {
                new ProductItem("ANCHOR 624000", "1/4#", "ANCHOR MOZZ STICK BREADED"),
                new ProductItem("ANCHOR POPPER", "1/4#", "ANCHOR JALAPENO POPPERS"),
                new ProductItem("BUTCHER BOY 10000", "72/4.5oz.", "BUTCHER BOY BEEF & BEAN /RC 72"),
                new ProductItem("BUTCHER BOY 1033201", "72/4oz.", "BEAN&CHEESE BURRITO"),
                new ProductItem("BUTCHER BOY 18300", "72/4.25oz.", "BUTCHER BOY BBQ SNACK BURRITO"),
                new ProductItem("CH BREAST TENDER", "40#", "CHICKEN BREAST TENDERS JUMBO"),
                new ProductItem("CH KOCH 86614", "2/7.5#", "KOCH WING F/C BRD PARTY WING"),
                new ProductItem("CH KOCH 86616", "15#", "KOCH WING SPICY BREADED F/C"),
                new ProductItem("CH TY7888", "72/2.7oz.", "TY7888 CHCKEN CRISPITOS 72/2.7"),
                new ProductItem("EG ROUND EGG PATTY", "120/1.5oz", "ROUND EGG PATTY 3.5\""),
                new ProductItem("FIR", "72/4oz.", "FOSTER FARMS CORNDOGS 4oz 72C"),
                new ProductItem("FIRJ", "36/4oz.", "FOSTER FARMS CHEESE AND JALAPE"),
                new ProductItem("FOSTER FARMS 5102", "72/4oz.", "RED CHILI BEEF & BEAN BURRITO"),
                new ProductItem("FOSTER FARMS 5183", "72/4.25oz.", "BBQ SNACK BURRITO #5183"),
                new ProductItem("FRED MINI TACO CH", "1/4#", "FRED'S MINI CHICKEN TACOS 4#"),
                new ProductItem("HORMEL BB HAM EGG", "80/2oz", "HORMEL HAM,EGG,CHEESE BREAKFAS"),
                new ProductItem("HORMEL BB SAU EGG CH", "72/2.25oz.", "HORMEL SAUSAGE,EGG,CHEESE COMB"),
                new ProductItem("HPPIZZS", "48/3oz", "HOT POCKET PEPPERONI PIZZA ST"),
                new ProductItem("J&J T71 PIZZA POCKET", "48/6oz", "J&J SUPREME STUFFERS"),
                new ProductItem("WAMPLER 90080", "10#", "8-1 PRECOOKED SAUSAGE PATTIES")
            };

            return products;
        }

    }
}
